"""
Slaves API - DNS Slave server management endpoints
"""
from flask import Blueprint, request, jsonify, current_app
import os
import re
import subprocess

from models import Slave, SlaveToken, audit_log
from api.auth import token_required, admin_required

slaves_api = Blueprint('slaves_api', __name__, url_prefix='/api/slaves')


# ============================================
# Public endpoints (for slave registration)
# ============================================

@slaves_api.route('/zones', methods=['GET'])
def get_zones_for_sync():
    """
    Get list of zones for slave synchronization.
    Public endpoint - only returns zone names and types.
    Used by slave sync script.
    """
    from services.dns_service import DNSService
    dns = DNSService()
    zones = dns.list_zones()

    # Only return master zones (slaves should sync these)
    master_zones = [
        {'name': z['name'], 'type': z.get('type', 'master'), 'file': z.get('file', f"db.{z['name']}")}
        for z in zones if z.get('type', 'master') == 'master'
    ]

    return jsonify({
        'zones': master_zones,
        'total': len(master_zones)
    })


@slaves_api.route('/config', methods=['GET'])
def get_slave_config():
    """
    Get configuration for slave installation.
    Requires valid integration token.
    Called by install-slave.sh script.
    """
    token_value = request.args.get('token')

    if not token_value:
        return jsonify({'error': 'Token required'}), 401

    # Validate token
    token = SlaveToken.get_by_token(token_value)

    if not token:
        return jsonify({'error': 'Invalid token'}), 401

    if not token.is_valid():
        return jsonify({'error': 'Token expired or already used'}), 401

    # Get RNDC key content
    rndc_key_path = current_app.config.get('RNDC_KEY_PATH', '/etc/bind/rndc.key')
    rndc_key_content = ''

    try:
        if os.path.exists(rndc_key_path):
            with open(rndc_key_path, 'r') as f:
                rndc_key_content = f.read()
    except Exception as e:
        current_app.logger.error(f"Error reading RNDC key: {e}")
        return jsonify({'error': 'Could not read RNDC key'}), 500

    # Get list of zones for slave configuration
    from services.dns_service import DNSService
    dns = DNSService()
    zones = dns.list_zones()

    # Get master IP (for slave configuration)
    master_ip = request.host.split(':')[0]  # Get hostname/IP from request

    # Read shared slave-agent token so the slave can authenticate push
    # requests from the master (and vice-versa). Generated by install.sh
    # on master install; same secret across all slaves.
    agent_token = ''
    agent_token_path = current_app.config.get(
        'SLAVE_AGENT_TOKEN_PATH', '/opt/dns-manager/slave-agent.token'
    )
    try:
        if os.path.exists(agent_token_path):
            with open(agent_token_path, 'r') as f:
                agent_token = f.read().strip()
    except Exception as e:
        current_app.logger.warning(f"Could not read slave-agent token: {e}")

    # Return configuration
    return jsonify({
        'rndc_key': rndc_key_content,
        'master_ip': master_ip,
        'zones': [{'name': z['name'], 'file': z['file']} for z in zones],
        'bind_config_dir': current_app.config.get('BIND_CONFIG_DIR', '/etc/bind'),
        'zones_path': current_app.config.get('ZONES_PATH', '/var/lib/bind/zones'),
        'slave_agent_token': agent_token,
    })


@slaves_api.route('/register', methods=['POST'])
def register_slave():
    """
    Register a new slave server.
    Called by install-slave.sh after successful configuration.
    """
    data = request.get_json()

    if not data:
        return jsonify({'error': 'No data provided'}), 400

    token_value = data.get('token')
    slave_ip = data.get('ip_address') or request.remote_addr
    hostname = data.get('hostname')

    if not token_value:
        return jsonify({'error': 'Token required'}), 401

    # Validate token
    token = SlaveToken.get_by_token(token_value)

    if not token:
        return jsonify({'error': 'Invalid token'}), 401

    if not token.is_valid():
        return jsonify({'error': 'Token expired or already used'}), 401

    # Check if slave already exists
    existing = Slave.get_by_ip(slave_ip)
    if existing:
        # Update existing slave
        existing.hostname = hostname
        existing.set_status('active')
        existing.update_last_seen()
        slave = existing
    else:
        # Create new slave
        slave = Slave.create(
            ip_address=slave_ip,
            hostname=hostname,
            notes=f'Registered via token {token.token[:8]}...'
        )

    # Mark token as used
    token.mark_used(slave_ip)

    # Update BIND configuration to allow transfer to this slave
    update_result = update_bind_allow_transfer()

    audit_log(
        'slave_registered',
        'slave',
        slave_ip,
        new_value={'hostname': hostname, 'token_id': token.id}
    )

    return jsonify({
        'message': 'Slave registered successfully',
        'slave': slave.to_dict(),
        'bind_updated': update_result
    })


@slaves_api.route('/heartbeat', methods=['POST'])
def slave_heartbeat():
    """
    Heartbeat endpoint for slaves to report status.
    """
    data = request.get_json() or {}
    slave_ip = data.get('ip_address') or request.remote_addr

    slave = Slave.get_by_ip(slave_ip)

    if not slave:
        return jsonify({'error': 'Slave not registered'}), 404

    slave.update_last_seen()

    # Update sync time if provided
    if data.get('last_sync'):
        slave.update_last_sync()

    return jsonify({
        'status': 'ok',
        'slave': slave.to_dict()
    })


# ============================================
# Admin endpoints (require authentication)
# ============================================

@slaves_api.route('', methods=['GET'])
@token_required
@admin_required
def list_slaves(current_user):
    """List all registered slaves"""
    slaves = Slave.get_all()
    return jsonify({
        'slaves': [s.to_dict() for s in slaves],
        'total': len(slaves)
    })


@slaves_api.route('/<int:slave_id>', methods=['GET'])
@token_required
@admin_required
def get_slave(current_user, slave_id):
    """Get a specific slave"""
    slave = Slave.query.get(slave_id)

    if not slave:
        return jsonify({'error': 'Slave not found'}), 404

    return jsonify(slave.to_dict())


@slaves_api.route('/<int:slave_id>', methods=['DELETE'])
@token_required
@admin_required
def delete_slave(current_user, slave_id):
    """Remove a slave"""
    slave = Slave.query.get(slave_id)

    if not slave:
        return jsonify({'error': 'Slave not found'}), 404

    ip_address = slave.ip_address
    slave.delete()

    # Update BIND configuration
    update_bind_allow_transfer()

    audit_log(
        'slave_deleted',
        'slave',
        ip_address,
        user=current_user
    )

    return jsonify({'message': 'Slave removed successfully'})


@slaves_api.route('/<int:slave_id>/status', methods=['PUT'])
@token_required
@admin_required
def update_slave_status(current_user, slave_id):
    """Update slave status"""
    slave = Slave.query.get(slave_id)

    if not slave:
        return jsonify({'error': 'Slave not found'}), 404

    data = request.get_json()
    new_status = data.get('status')

    if new_status not in ['active', 'inactive', 'pending', 'error']:
        return jsonify({'error': 'Invalid status'}), 400

    old_status = slave.status
    slave.set_status(new_status)

    # Update BIND if status changed to/from active
    if (old_status == 'active') != (new_status == 'active'):
        update_bind_allow_transfer()

    audit_log(
        'slave_status_changed',
        'slave',
        slave.ip_address,
        old_value={'status': old_status},
        new_value={'status': new_status},
        user=current_user
    )

    return jsonify(slave.to_dict())


# ============================================
# Token management
# ============================================

@slaves_api.route('/tokens', methods=['GET'])
@token_required
@admin_required
def list_tokens(current_user):
    """List all active integration tokens"""
    # Cleanup expired tokens first
    SlaveToken.cleanup_expired()

    tokens = SlaveToken.get_active()
    return jsonify({
        'tokens': [t.to_dict() for t in tokens],
        'total': len(tokens)
    })


@slaves_api.route('/tokens', methods=['POST'])
@token_required
@admin_required
def generate_token(current_user):
    """Generate a new integration token"""
    data = request.get_json() or {}
    expiry_minutes = data.get('expiry_minutes',
        current_app.config.get('SLAVE_TOKEN_EXPIRY_MINUTES', 60))

    # Limit expiry to max 24 hours (1440 minutes)
    expiry_minutes = min(expiry_minutes, 1440)

    token = SlaveToken.generate(
        user_id=current_user.id,
        expiry_minutes=expiry_minutes
    )

    audit_log(
        'slave_token_generated',
        'slave_token',
        token.token[:8],
        new_value={'expiry_minutes': expiry_minutes},
        user=current_user
    )

    # Build the installation command
    master_url = request.host_url.rstrip('/')
    install_command = f"curl -sSL {master_url}/install-slave.sh | sudo bash -s -- --master={request.host.split(':')[0]} --token={token.token}"

    return jsonify({
        'token': token.to_dict(),
        'install_command': install_command
    })


@slaves_api.route('/tokens/<int:token_id>', methods=['DELETE'])
@token_required
@admin_required
def revoke_token(current_user, token_id):
    """Revoke an integration token"""
    token = SlaveToken.query.get(token_id)

    if not token:
        return jsonify({'error': 'Token not found'}), 404

    from models import db
    db.session.delete(token)
    db.session.commit()

    audit_log(
        'slave_token_revoked',
        'slave_token',
        token.token[:8],
        user=current_user
    )

    return jsonify({'message': 'Token revoked'})


# ============================================
# Helper functions
# ============================================

def update_bind_allow_transfer():
    """
    Update BIND configuration to allow zone transfers to active slaves.
    Returns True if successful, error message otherwise.
    """
    try:
        # Get all active slave IPs
        active_slaves = Slave.get_active()
        slave_ips = [s.ip_address for s in active_slaves]

        if not slave_ips:
            slave_ips = ['none']

        # Read current named.conf.local
        named_conf_local = current_app.config.get('NAMED_CONF_LOCAL')

        if not os.path.exists(named_conf_local):
            return "Named config not found"

        with open(named_conf_local, 'r') as f:
            content = f.read()

        # Update or add slaves ACL
        slaves_acl = 'acl "slaves" {\n'
        for ip in slave_ips:
            if ip != 'none':
                slaves_acl += f'    {ip};\n'
        slaves_acl += '};\n'

        # Check if ACL exists
        acl_pattern = r'acl\s+"slaves"\s*\{[^}]*\};'

        if re.search(acl_pattern, content):
            # Update existing ACL
            content = re.sub(acl_pattern, slaves_acl.strip(), content)
        else:
            # Add ACL at the beginning
            content = slaves_acl + '\n' + content

        # Update allow-transfer in zone blocks
        # Pattern: allow-transfer { ... };
        transfer_pattern = r'allow-transfer\s*\{[^}]*\}'

        if slave_ips and slave_ips[0] != 'none':
            new_transfer = 'allow-transfer { slaves; }'
        else:
            new_transfer = 'allow-transfer { none; }'

        content = re.sub(transfer_pattern, new_transfer, content)

        # Write updated config
        with open(named_conf_local, 'w') as f:
            f.write(content)

        # Reload BIND
        from services.dns_service import DNSService
        dns = DNSService()
        success, msg = dns.reload_all()

        if success:
            return True
        else:
            return f"Config updated but reload failed: {msg}"

    except Exception as e:
        current_app.logger.error(f"Error updating BIND config: {e}")
        return str(e)


def check_slave_connectivity(ip_address):
    """
    Check if we can connect to a slave's DNS port.
    """
    try:
        result = subprocess.run(
            ['dig', '+short', '+time=2', f'@{ip_address}', 'version.bind', 'chaos', 'txt'],
            capture_output=True,
            text=True,
            timeout=5
        )
        return result.returncode == 0
    except Exception:
        return False
