"""
PRIVUM DNS Manager - Slave Notifier Service

Pushes zone CRUD events from master to all registered slaves' agent endpoints.
Best-effort: failures are logged but never block the API response. Slaves
reconcile themselves at startup via /api/slaves/zones so missed pushes are
self-healing without a cron job.
"""
import logging
import threading
from typing import Optional

import requests

from models.slave import Slave

log = logging.getLogger(__name__)

# Path to the shared secret between master and all slave agents.
# Generated by install.sh at master install time.
AGENT_TOKEN_PATH = "/opt/dns-manager/slave-agent.token"
DEFAULT_AGENT_PORT = 5001
PUSH_TIMEOUT_SECONDS = 8


def _load_token() -> Optional[str]:
    try:
        with open(AGENT_TOKEN_PATH) as f:
            tok = f.read().strip()
            return tok or None
    except FileNotFoundError:
        log.warning(
            "Slave-agent token not found at %s — slave push disabled. "
            "Generate one with `openssl rand -hex 32 > %s` and restart the API.",
            AGENT_TOKEN_PATH, AGENT_TOKEN_PATH,
        )
        return None
    except Exception as exc:
        log.error("Failed to read slave-agent token: %s", exc)
        return None


def _slave_url(slave: Slave, path: str) -> str:
    return f"http://{slave.ip_address}:{DEFAULT_AGENT_PORT}{path}"


def _push_add(slave: Slave, zone_name: str, zone_file: str, token: str) -> None:
    try:
        r = requests.post(
            _slave_url(slave, "/zones"),
            headers={"Authorization": f"Bearer {token}"},
            json={"name": zone_name, "file": zone_file},
            timeout=PUSH_TIMEOUT_SECONDS,
        )
        if r.status_code >= 400:
            log.warning(
                "Slave %s rejected add %s: HTTP %d %s",
                slave.ip_address, zone_name, r.status_code, r.text[:200],
            )
        else:
            log.info("Slave %s: added %s", slave.ip_address, zone_name)
    except Exception as exc:
        log.warning("Push add %s -> %s failed: %s", zone_name, slave.ip_address, exc)


def _push_delete(slave: Slave, zone_name: str, token: str) -> None:
    try:
        r = requests.delete(
            _slave_url(slave, f"/zones/{zone_name}"),
            headers={"Authorization": f"Bearer {token}"},
            timeout=PUSH_TIMEOUT_SECONDS,
        )
        if r.status_code >= 400:
            log.warning(
                "Slave %s rejected delete %s: HTTP %d %s",
                slave.ip_address, zone_name, r.status_code, r.text[:200],
            )
        else:
            log.info("Slave %s: deleted %s", slave.ip_address, zone_name)
    except Exception as exc:
        log.warning("Push delete %s -> %s failed: %s", zone_name, slave.ip_address, exc)


def _fanout(targets: list[Slave], func, *args) -> None:
    """Run `func(slave, *args)` against every target in parallel daemon threads.
    Daemon threads are fine — even if API process exits, slaves can be
    re-reconciled on their next startup."""
    for slave in targets:
        threading.Thread(target=func, args=(slave, *args), daemon=True).start()


# ---------------------------------------------------------------------------
# Public API — call these from api/zones.py
# ---------------------------------------------------------------------------
def notify_zone_added(zone_name: str, zone_file: Optional[str] = None) -> None:
    """Fire-and-forget push to all active slaves to add this zone as secondary."""
    token = _load_token()
    if not token:
        return
    slaves = Slave.get_active()
    if not slaves:
        return
    zone_file = zone_file or f"db.{zone_name}"
    _fanout(slaves, _push_add, zone_name, zone_file, token)


def notify_zone_deleted(zone_name: str) -> None:
    """Fire-and-forget push to all active slaves to remove this zone."""
    token = _load_token()
    if not token:
        return
    slaves = Slave.get_active()
    if not slaves:
        return
    _fanout(slaves, _push_delete, zone_name, token)
