#!/bin/bash
#
# DNS Web Manager - Setup Script
# Detects environment and configures automatically
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "================================================"
echo "   DNS Web Manager - Automatic Setup"
echo "================================================"
echo -e "${NC}"

# Detect environment
detect_environment() {
    if grep -qi microsoft /proc/version 2>/dev/null; then
        echo "wsl2"
    elif [ -f /etc/os-release ]; then
        if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
            echo "linux-resolved"
        else
            echo "linux-clean"
        fi
    else
        echo "unknown"
    fi
}

# Check if port is available
check_port() {
    local port=$1
    if ss -tlnp 2>/dev/null | grep -q ":${port} " || netstat -tlnp 2>/dev/null | grep -q ":${port} "; then
        return 1  # Port in use
    fi
    return 0  # Port available
}

# Create .env file
create_env_file() {
    local dns_master_port=$1
    local dns_slave_port=$2

    cat > .env << EOF
# DNS Web Manager - Environment Configuration
# Auto-generated by setup.sh on $(date)

# DNS Ports (default: 53 for production)
DNS_MASTER_PORT=${dns_master_port}
DNS_SLAVE_PORT=${dns_slave_port}

# Security (CHANGE IN PRODUCTION!)
SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || echo "change-me-in-production-$(date +%s)")
DB_PASSWORD=dnsmanager123

# Backup
NFS_BACKUP_PATH=./backups

# Timezone
TZ=UTC
EOF
    echo -e "${GREEN}✓ .env file created${NC}"
}

# Configure dnsmasq for proxy
setup_dnsmasq() {
    local dns_port=$1

    echo -e "${YELLOW}→ Configuring dnsmasq as DNS proxy...${NC}"

    if ! command -v dnsmasq &> /dev/null; then
        echo -e "${YELLOW}  Installing dnsmasq...${NC}"
        sudo apt-get update -qq && sudo apt-get install -y -qq dnsmasq
    fi

    # Create configuration
    sudo tee /etc/dnsmasq.d/dns-manager.conf > /dev/null << EOF
# DNS Web Manager - Proxy to container
# Redirects specific domains to DNS Master on port ${dns_port}

# Add your domains here:
# server=/yourdomain.com/127.0.0.1#${dns_port}

# Example domains (edit as needed)
server=/example.com/127.0.0.1#${dns_port}
server=/test.local/127.0.0.1#${dns_port}
server=/20.172.in-addr.arpa/127.0.0.1#${dns_port}
EOF

    sudo systemctl restart dnsmasq
    sudo systemctl enable dnsmasq

    echo -e "${GREEN}✓ dnsmasq configured${NC}"
    echo -e "${YELLOW}  To add new domains, edit: /etc/dnsmasq.d/dns-manager.conf${NC}"
}

# Main
main() {
    ENV_TYPE=$(detect_environment)

    echo -e "Detected environment: ${BLUE}${ENV_TYPE}${NC}"
    echo ""

    case $ENV_TYPE in
        "linux-clean")
            echo -e "${GREEN}✓ Ideal environment! Port 53 is probably available.${NC}"

            if check_port 53; then
                echo -e "${GREEN}✓ Port 53 is available!${NC}"
                create_env_file 53 54
                echo ""
                echo -e "${GREEN}Ready! Run:${NC}"
                echo "  docker compose up -d"
            else
                echo -e "${YELLOW}⚠ Port 53 is in use. Using alternative port.${NC}"
                create_env_file 5300 5353
                echo ""
                echo -e "${YELLOW}Port 53 is in use. Options:${NC}"
                echo "  1. Find what's using it: sudo ss -tlnp | grep :53"
                echo "  2. Or use with alternative port: docker compose up -d"
            fi
            ;;

        "linux-resolved")
            echo -e "${YELLOW}⚠ systemd-resolved detected (port 53 in use)${NC}"
            echo ""
            echo "Options:"
            echo "  1) Disable systemd-resolved (recommended for servers)"
            echo "  2) Use alternative port + dnsmasq (recommended for desktop)"
            echo "  3) Cancel"
            echo ""
            read -p "Choose [1/2/3]: " choice

            case $choice in
                1)
                    echo -e "${YELLOW}→ Disabling systemd-resolved...${NC}"
                    sudo systemctl stop systemd-resolved
                    sudo systemctl disable systemd-resolved
                    # Backup and recreate resolv.conf
                    sudo cp /etc/resolv.conf /etc/resolv.conf.backup
                    echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
                    create_env_file 53 54
                    echo -e "${GREEN}✓ systemd-resolved disabled${NC}"
                    echo -e "${YELLOW}  After starting containers, edit /etc/resolv.conf to use 127.0.0.1${NC}"
                    ;;
                2)
                    create_env_file 5300 5353
                    setup_dnsmasq 5300
                    ;;
                *)
                    echo "Cancelled."
                    exit 0
                    ;;
            esac
            ;;

        "wsl2")
            echo -e "${YELLOW}⚠ WSL2 detected (port 53 in use by Windows)${NC}"
            echo ""
            create_env_file 5300 5353

            echo "Do you want to configure dnsmasq for proxy? (recommended)"
            read -p "[y/N]: " setup_proxy

            if [[ $setup_proxy =~ ^[Yy]$ ]]; then
                setup_dnsmasq 5300
            else
                echo -e "${YELLOW}To resolve domains, configure manually:${NC}"
                echo "  - Use dig @localhost -p 5300 domain.com"
                echo "  - Or configure dnsmasq later"
            fi
            ;;

        *)
            echo -e "${YELLOW}⚠ Unknown environment. Using default configuration.${NC}"
            create_env_file 53 54
            ;;
    esac

    echo ""
    echo -e "${BLUE}================================================${NC}"
    echo -e "${GREEN}Setup complete!${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Review the .env file"
    echo "  2. Run: docker compose up -d"
    echo "  3. Access: http://localhost:8080"
    echo "  4. Login: admin / admin123"
    echo -e "${BLUE}================================================${NC}"
}

main "$@"
